#!/bin/fish
set -Ux fish_color_autosuggestion 7596E4
set -Ux fish_color_cancel \x2dr
set -Ux fish_color_command 164CC9
set -Ux fish_color_comment 007B7B
set -Ux fish_color_cwd green
set -Ux fish_color_cwd_root red
set -Ux fish_color_end 02BDBD
set -Ux fish_color_error 9177E5
set -Ux fish_color_escape 00a6b2
set -Ux fish_color_hg_added green
set -Ux fish_color_hg_clean green
set -Ux fish_color_hg_copied magenta
set -Ux fish_color_hg_deleted red
set -Ux fish_color_hg_dirty red
set -Ux fish_color_hg_modified yellow
set -Ux fish_color_hg_renamed magenta
set -Ux fish_color_hg_unmerged red
set -Ux fish_color_hg_untracked yellow
set -Ux fish_color_history_current \x2d\x2dbold
set -Ux fish_color_host normal
set -Ux fish_color_host_remote yellow
set -Ux fish_color_keyword 164CC9
set -Ux fish_color_match \x2d\x2dbackground\x3dbrblue
set -Ux fish_color_normal normal
set -Ux fish_color_operator 00a6b2
set -Ux fish_color_option 4319CC
set -Ux fish_color_param 4319CC
set -Ux fish_color_quote 4C3499
set -Ux fish_color_redirection 248E8E
set -Ux fish_color_search_match bryellow\x1e\x2d\x2dbackground\x3dbrblack
set -Ux fish_color_selection white\x1e\x2d\x2dbold\x1e\x2d\x2dbackground\x3dbrblack
set -Ux fish_color_status red
set -Ux fish_color_user brgreen
set -Ux fish_color_valid_path \x2d\x2dunderline
set -Ux fish_pager_color_background \x1d
set -Ux fish_pager_color_completion normal
set -Ux fish_pager_color_description B3A06D\x1eyellow
set -Ux fish_pager_color_prefix normal\x1e\x2d\x2dbold\x1e\x2d\x2dunderline
set -Ux fish_pager_color_progress brwhite\x1e\x2d\x2dbackground\x3dcyan
set -Ux fish_pager_color_secondary_background \x1d
set -Ux fish_pager_color_secondary_completion \x1d
set -Ux fish_pager_color_secondary_description \x1d
set -Ux fish_pager_color_secondary_prefix \x1d
set -Ux fish_pager_color_selected_background \x2d\x2dbackground\x3dbrblack
set -Ux fish_pager_color_selected_completion \x1d
set -Ux fish_pager_color_selected_description \x1d
set -Ux fish_pager_color_selected_prefix \x1d
